<?php

use Illuminate\Database\Seeder;

use App\Repositories\Ward\EloquentWardRepository;
use App\Repositories\LocalGovernment\EloquentLocalGovernmentRepository;
use App\Repositories\RedemptionCenter\EloquentRedemptionCenterRepository;

class LocalGovernmentsTableSeeder extends Seeder
{
    protected $localGovernmentModel;
    protected $wardModel;
    protected $rCenterModel;
    public function __construct(EloquentLocalGovernmentRepository $localGovernmentContract, EloquentWardRepository $wardContract,
    EloquentRedemptionCenterRepository $redemptionCenterContract) {
        $this->localGovernmentModel = $localGovernmentContract;
        $this->wardModel = $wardContract;
        $this->rCenterModel = $redemptionCenterContract;
    }

    public function run()
    {
        $lga1 = $this->localGovernmentModel->create('BARKI LADI LGA');
        $center1 = $this->rCenterModel->create('NO.9A ONOJA RD.B/LADI');
        $ward1 = $this->wardModel->create('LOBIRING', $lga1, $center1);
        $ward2 = $this->wardModel->create('ROFAN', $lga1, $center1);
        $center2 = $this->rCenterModel->create('NO.5A ONOJA RD.B/LADI');
        $ward3 = $this->wardModel->create('KARAFALLS', $lga1, $center2);
        $ward4 = $this->wardModel->create('GINDIN AKWATI', $lga1, $center2);
        $ward5 = $this->wardModel->create('MARIT/AMZAT', $lga1, $center2);
        $center3 = $this->rCenterModel->create('RAT');
        $ward6 = $this->wardModel->create('KAPWIS', $lga1, $center3);
        $ward7 = $this->wardModel->create('ZABOT', $lga1, $center3);
        $center4 = $this->rCenterModel->create('PADP STORE B/LADI');
        $ward8 = $this->wardModel->create('HEIPANG', $lga1, $center4);
        $ward9 = $this->wardModel->create('GASSA/SHO', $lga1, $center4);
        $center5 = $this->rCenterModel->create('B/LADI TOWN');
        $ward10 = $this->wardModel->create('B/LADI A', $lga1, $center5);
        $ward11 = $this->wardModel->create('B/LADI B', $lga1, $center5);

        $lga2 = $this->localGovernmentModel->create('BASSA LGA');
        $center6 = $this->rCenterModel->create('PADP STORE MBS');
        $ward12 = $this->wardModel->create('BUHIT', $lga2, $center6);
        $ward13 = $this->wardModel->create(' MARAFA', $lga2, $center6);
        $center7 = $this->rCenterModel->create('PADP STORE NUMAS');
        $ward14 = $this->wardModel->create('KISHAKA', $lga2, $center7);
        $ward15 = $this->wardModel->create('KAKKEH', $lga2, $center7);
        $center8 = $this->rCenterModel->create('PADP STORE MIANGO NUNAS');
        $ward16 = $this->wardModel->create('TUHU', $lga2, $center8);
        $ward17 = $this->wardModel->create('KIMAPKA', $lga2, $center8);
        $ward18 = $this->wardModel->create('GABIA', $lga2, $center8);
        $center9 = $this->rCenterModel->create('PADP STORE MIANGO NUNAS');
        $ward19 = $this->wardModel->create('ZABIRO', $lga2, $center9);
        $ward20 = $this->wardModel->create('TAAGBE', $lga2, $center9);
        $center10 = $this->rCenterModel->create('PADP STORE JENGRE NUNAS');
        $ward21 = $this->wardModel->create('KASURU', $lga2, $center10);
        $ward22 = $this->wardModel->create('RIMI', $lga2, $center10);
        $ward23 = $this->wardModel->create('JENGRE', $lga2, $center10);
        $center11 = $this->rCenterModel->create('MISTA ALI TOWN');
        $ward24 = $this->wardModel->create('GURUM', $lga2, $center11);
        $ward25 = $this->wardModel->create('BUJI', $lga2, $center11);
        $ward26 = $this->wardModel->create('ZABOLO', $lga2, $center11);

        $lga3 = $this->localGovernmentModel->create('BOKKOS LGA');
        $center12 = $this->rCenterModel->create('PADP STORE 1  BOKKOS NUNAS');
        $ward27 = $this->wardModel->create('MUSH/EAST', $lga3, $center12);
        $ward28 = $this->wardModel->create('MUSH/WEST', $lga3, $center12);
        $center13 = $this->rCenterModel->create('PADP STORE 1  BOKKOS NUNAS');
        $ward29 = $this->wardModel->create('TANKUR', $lga3, $center13);
        $center14 = $this->rCenterModel->create('PADP STORE 2  BOKKOS NUNAS');
        $ward30 = $this->wardModel->create('BOKKOS', $lga3, $center14);
        $center15 = $this->rCenterModel->create('PADP STORE 2  BOKKOS NUNAS');
        $ward31 = $this->wardModel->create('BUTURA', $lga3, $center15);
        $center16 = $this->rCenterModel->create('MOA STORE 1 BOKKOS SHANKAT');
        $ward32 = $this->wardModel->create('SHA', $lga3, $center16);
        $ward33 = $this->wardModel->create(' RICHA', $lga3, $center16);
        $center17 = $this->rCenterModel->create('MOA STORE 2 BOKKOS MBS');
        $ward34 = $this->wardModel->create('MANGUNA', $lga3, $center17);
        $center18 = $this->rCenterModel->create('BOKKOS TOWN');
        $ward35 = $this->wardModel->create('KWATAS', $lga3, $center18);
        $ward36 = $this->wardModel->create('MANGOR', $lga3, $center18);
        $center19 = $this->rCenterModel->create('BOKKOS TOWN');
        $ward37 = $this->wardModel->create('MBAR/MANGER', $lga3, $center19);
        $center20 = $this->rCenterModel->create('MOA STOR 2 BOKKOS MBS');
        $ward38 = $this->wardModel->create('KAMWAL', $lga3, $center20);
        $ward39 = $this->wardModel->create('TOFF', $lga3, $center20);
        $ward40 = $this->wardModel->create('DAFFO', $lga3, $center20);

        $lga4 = $this->localGovernmentModel->create('JOS EAST');
        $center21 = $this->rCenterModel->create('PADP STORE 1');
        $ward41 = $this->wardModel->create('FOBUR A', $lga4, $center21);
        $ward42 = $this->wardModel->create('FOBUR B', $lga4, $center21);
        $center22 = $this->rCenterModel->create('PADP STORE 1');
        $ward43 = $this->wardModel->create('SHERE EAST', $lga4, $center22);
        $ward44 = $this->wardModel->create('SHERE WEST', $lga4, $center22);
        $center23 = $this->rCenterModel->create('FOBUR TOWN');
        $ward45 = $this->wardModel->create('FURSUM', $lga4, $center23);
        $ward46 = $this->wardModel->create('MAIJUJU', $lga4, $center23);
        $center24 = $this->rCenterModel->create('FOBUR TOWN');
        $ward47 = $this->wardModel->create('ZANDI', $lga4, $center24);
        $ward48 = $this->wardModel->create('FEDERE', $lga4, $center24);
        $center25 = $this->rCenterModel->create('FEDERE TOWN');
        $ward49 = $this->wardModel->create('MAIGEMU', $lga4, $center25);
        $ward50 = $this->wardModel->create('JARAWA KOGI 4', $lga4, $center25);

        $lga5 = $this->localGovernmentModel->create('JOS NORTH');
        $center26 = $this->rCenterModel->create('PADP STORE');
        $ward51 = $this->wardModel->create('T/BALEWA', $lga5, $center26);
        $center27 = $this->rCenterModel->create('DOGON DUTSE');
        $ward52 = $this->wardModel->create('T/WADA/KABONG', $lga5, $center27);
        $center28 = $this->rCenterModel->create('POLO STORE');
        $ward53 = $this->wardModel->create('VANDEPUYE', $lga5, $center28);
        $ward54 = $this->wardModel->create('JENTA ADAMU', $lga5, $center28);
        $ward55 = $this->wardModel->create('SAKIN ARAB', $lga5, $center28);
        $center29 = $this->rCenterModel->create('PLATEAU SUPPLY COMPANY STORE DOGON DUTSE');
        $ward56 = $this->wardModel->create('NARAGUTA A', $lga5, $center29);
        $ward57 = $this->wardModel->create('NARAGUTA B', $lga5, $center29);
        $center30 = $this->rCenterModel->create('DOGON DUTSE STORE 4');
        $ward58 = $this->wardModel->create('ABBA NA SHEHU', $lga5, $center30);
        $ward59 = $this->wardModel->create('GANGARE 4', $lga5, $center30);
        $center31 = $this->rCenterModel->create('DOGON DUTSE JOS');
        $ward60 = $this->wardModel->create('GARBADAHO', $lga5, $center31);
        $ward61 = $this->wardModel->create('ALIKAZAURE', $lga5, $center31);
        $ward62 = $this->wardModel->create('JENTA APATA', $lga5, $center31);
        $center32 = $this->rCenterModel->create('DOGON DUTSE STORE 2');
        $ward63 = $this->wardModel->create('JOS JARAWA', $lga5, $center32);
        $ward64 = $this->wardModel->create('IBRAHIM KATSINA', $lga5, $center32);

        $lga6 = $this->localGovernmentModel->create('JOS SOUTH');
        $center33 = $this->rCenterModel->create('AGRO PROD.OPP VIO OFFICE MBS');
        $ward65 = $this->wardModel->create('GIRIN', $lga6, $center33);
        $center34 = $this->rCenterModel->create('AGRO PROD.OPP VIO OFFICE MBS');
        $ward66 = $this->wardModel->create('ZAWAN A', $lga6, $center34);
        $ward67 = $this->wardModel->create('ZAWAN B', $lga6, $center34);
        $center35 = $this->rCenterModel->create('TRADE CENTER KARU MBS');
        $ward68 = $this->wardModel->create('KURU A', $lga6, $center35);
        $ward69 = $this->wardModel->create('KURU B', $lga6, $center35);
        $center36 = $this->rCenterModel->create('MOA STORE 2 BUKURU MBS');
        $ward70 = $this->wardModel->create('GYEL A', $lga6, $center36);
        $ward71 = $this->wardModel->create('GYEL B', $lga6, $center36);
        $center37 = $this->rCenterModel->create('MOA STORE 1 BUKURU MBS');
        $ward72 = $this->wardModel->create('DU SHEN', $lga6, $center37);
        $center38 = $this->rCenterModel->create('MOA STORE 1 BUKURU MBS');
        $ward73 = $this->wardModel->create('BUKURU', $lga6, $center38);
        $center39 = $this->rCenterModel->create('FARIN LAMBA');
        $ward74 = $this->wardModel->create('VWANG TURU', $lga6, $center39);

        $lga7 = $this->localGovernmentModel->create('KANAM LGC');
        $center40 = $this->rCenterModel->create('NO. 1 WASE RD DENGI SHANKAT');
        $ward75 = $this->wardModel->create('KANAM', $lga7, $center40);
        $ward76 = $this->wardModel->create('GAGDI', $lga7, $center40);
        $ward77 = $this->wardModel->create('DUGUB', $lga7, $center40);
        $center41 = $this->rCenterModel->create('MOA STORE I DENGI SHANKAT');
        $ward78 = $this->wardModel->create('WARDS: DENGI', $lga7, $center41);
        $ward79 = $this->wardModel->create('GAR', $lga7, $center41);
        $center42 = $this->rCenterModel->create('MOA STORE II DENGI NUNAS');
        $ward80 = $this->wardModel->create('GARGA', $lga7, $center42);
        $ward81 = $this->wardModel->create('BIRBYANG', $lga7, $center42);
        $ward82 = $this->wardModel->create('KANTANA', $lga7, $center42);
        $center43 = $this->rCenterModel->create('NO: 1 WASE RD DENGI NUNAS');
        $ward83 = $this->wardModel->create('JARMAI', $lga7, $center43);
        $ward84 = $this->wardModel->create('JOM', $lga7, $center43);
        $ward85 = $this->wardModel->create('BAGGER', $lga7, $center43);
        $center44 = $this->rCenterModel->create('NO: 1 WASE RD DENGI SHANKAT');
        $ward86 = $this->wardModel->create('KUNKYAM', $lga7, $center44);
        $ward87 = $this->wardModel->create('NAMARAM', $lga7, $center44);

        $lga8 = $this->localGovernmentModel->create('KANKE LGC');
        $center45 = $this->rCenterModel->create('DAWAKI TOWN SHANKAT');
        $ward88 = $this->wardModel->create('DAWAKI', $lga8, $center45);
        $ward89 = $this->wardModel->create('KABWIR PADA', $lga8, $center45);
        $ward90 = $this->wardModel->create(' NEMEL', $lga8, $center45);
        $center46 = $this->rCenterModel->create('TABULUNG VILLAGE SHANKAT');
        $ward91 = $this->wardModel->create('KANWIR/GYANGYANG', $lga8, $center46);
        $ward92 = $this->wardModel->create('TABULUNG VILLAGE', $lga8, $center46);
        $center47 = $this->rCenterModel->create('PADP STORE AMPER NUNAS');
        $ward93 = $this->wardModel->create('AMPER/CHIKA', $lga8, $center47);
        $ward94 = $this->wardModel->create('AMPER/SERI', $lga8, $center47);
        $ward95 = $this->wardModel->create('AMPER B', $lga8, $center47);
        $center48 = $this->rCenterModel->create('LANGSHI VILLAGE, KANKE');
        $ward96 = $this->wardModel->create('NUNAS', $lga8, $center48);

        $lga9 = $this->localGovernmentModel->create('LANGTAN/NORTH LGA');
        $center49 = $this->rCenterModel->create('GAYA WARE HOUSE WASE RD PAJAT(DADURA)NUNAS');
        $ward97 = $this->wardModel->create('JAT', $lga9, $center49);
        $ward98 = $this->wardModel->create('REAK', $lga9, $center49);
        $ward99 = $this->wardModel->create('KWAMPE', $lga9, $center49);
        $center50 = $this->rCenterModel->create('GAYA WARE HOUSE WASE RD PAJAT(PAJAT)NUNAS');
        $ward100 = $this->wardModel->create('PAJAT', $lga9, $center50);
        $ward101 = $this->wardModel->create('LIPCHOK', $lga9, $center50);
        $ward102 = $this->wardModel->create('TAMBAT', $lga9, $center50);
        $center51 = $this->rCenterModel->create('NEW MARKET RD NEAR CATHOLIC CHURCH LANGTANG (KUFFEN)NUNAS');
        $ward103 = $this->wardModel->create('KUFFEN', $lga9, $center51);
        $ward104 = $this->wardModel->create('ZAMKO/MBAN', $lga9, $center51);
        $ward105 = $this->wardModel->create('NYER', $lga9, $center51);
        $center52 = $this->rCenterModel->create('MOA STORE 2 LANGTANG (GAZUM)MBS');
        $ward106 = $this->wardModel->create('WAROK', $lga9, $center52);
        $ward107 = $this->wardModel->create('FUNYALLANG', $lga9, $center52);
        $ward108 = $this->wardModel->create(' KWALLAK', $lga9, $center52);
        $center53 = $this->rCenterModel->create('MOA STORE 2 LANGTANG (PILGANI)MBS');
        $ward109 = $this->wardModel->create('PILGANI', $lga9, $center53);
        $ward110 = $this->wardModel->create('KELLER', $lga9, $center53);
        $ward111 = $this->wardModel->create(' PISHE/ YASHI', $lga9, $center53);

        $lga10 = $this->localGovernmentModel->create('LANGTAN SOUTH LGA');
        $center54 = $this->rCenterModel->create('SABON GIDA TOWN MBS');
        $ward112 = $this->wardModel->create('MABUDI', $lga10, $center54);
        $center55 = $this->rCenterModel->create('SABON GIDA TOWN SHANKAT');
        $ward113 = $this->wardModel->create('GAMAKIA', $lga10, $center55);
        $ward114 = $this->wardModel->create('TALGWANG', $lga10, $center55);
        $center56 = $this->rCenterModel->create('MABUDI TOWN MBS');
        $ward115 = $this->wardModel->create('DADIN KOWA', $lga10, $center56);
        $center57 = $this->rCenterModel->create('MABUDI TOWN SHANKAT');
        $ward116 = $this->wardModel->create('FAJUL', $lga10, $center57);
        $ward117 = $this->wardModel->create('LASHEL', $lga10, $center57);
        $center58 = $this->rCenterModel->create('SABON GIDA TOWN L/SOUTH');
        $ward118 = $this->wardModel->create('SABON GIDA', $lga10, $center58);
        $ward119 = $this->wardModel->create('MAGAMA', $lga10, $center58);
        $center59 = $this->rCenterModel->create('SABON GIDA TOWN L/SOUTH');
        $ward120 = $this->wardModel->create('TIMBOL', $lga10, $center59);
        $ward121 = $this->wardModel->create('TURAKI', $lga10, $center59);

        $lga11 = $this->localGovernmentModel->create('MANGU LGC');
        $center60 = $this->rCenterModel->create('MARARABA PUSHIT MBS');
        $ward122 = $this->wardModel->create('JANARET', $lga11, $center60);
        $center61 = $this->rCenterModel->create('MARARABA PUSHIT MBS');
        $ward123 = $this->wardModel->create('PUSHIT', $lga11, $center61);
        $center62 = $this->rCenterModel->create('PADP  STORE MANGU NUNAS');
        $ward124 = $this->wardModel->create('MANGUN', $lga11, $center62);
        $ward125 = $this->wardModel->create('AMPANG WEST', $lga11, $center62);
        $center63 = $this->rCenterModel->create('BUNGA PNK RD MANGU MBS');
        $ward126 = $this->wardModel->create('MANGU I', $lga11, $center63);
        $ward127 = $this->wardModel->create('MANGU II', $lga11, $center63);
        $center64 = $this->rCenterModel->create('PANYAM TOWN MBS');
        $ward128 = $this->wardModel->create('PANYAM', $lga11, $center64);
        $center65 = $this->rCenterModel->create('OPP.INEC OFFICE MANGU MBS');
        $ward129 = $this->wardModel->create('KOMBUN', $lga11, $center65);
        $center66 = $this->rCenterModel->create('KASUWAN ALI MBS');
        $ward130 = $this->wardModel->create('GINDIRI I', $lga11, $center66);
        $ward131 = $this->wardModel->create('GINDIRI II', $lga11, $center66);
        $center67 = $this->rCenterModel->create('CHANSO TOWN SHANKAT');
        $ward132 = $this->wardModel->create('CHANSON', $lga11, $center67);
        $ward133 = $this->wardModel->create('LANGAI', $lga11, $center67);
        $center68 = $this->rCenterModel->create('PADP STORE II SHANKAT');
        $ward134 = $this->wardModel->create('JIPAL/CHAKFEM', $lga11, $center68);
        $center69 = $this->rCenterModel->create('PADP STORE II SHANKAT');
        $ward135 = $this->wardModel->create('KERANG', $lga11, $center69);
        $center70 = $this->rCenterModel->create('MANGU HALLE NUNAS');
        $ward136 = $this->wardModel->create('MANGU HALLE', $lga11, $center70);

        $lga12 = $this->localGovernmentModel->create('MIKANG LGC');
        $center71 = $this->rCenterModel->create('LIFIDI TOWN NUNAS');
        $ward137 = $this->wardModel->create('KONEOM A', $lga12, $center71);
        $ward138 = $this->wardModel->create('KONEOM B', $lga12, $center71);
        $center72 = $this->rCenterModel->create('GARKAWA TOWN NUNAS');
        $ward139 = $this->wardModel->create('GARKAWA CENTRAL', $lga12, $center72);
        $ward140 = $this->wardModel->create('GARKAWA NORTH', $lga12, $center72);
        $ward141 = $this->wardModel->create('WARKAWANORTH-EAST', $lga12, $center72);
        $center73 = $this->rCenterModel->create('PIAPUNG TOWN NUNAS');
        $ward142 = $this->wardModel->create('PIAPUNG A', $lga12, $center73);
        $ward143 = $this->wardModel->create('PIAPUNG B', $lga12, $center73);
        $center74 = $this->rCenterModel->create('TUNGKUS TOWN NUNAS');
        $ward144 = $this->wardModel->create('TUNGKUS', $lga12, $center74);
        $ward145 = $this->wardModel->create('LALIN', $lga12, $center74);
        $ward146 = $this->wardModel->create('BALTED', $lga12, $center74);

        $lga13 = $this->localGovernmentModel->create('PANKSHIN LGA');
        $center75 = $this->rCenterModel->create('MOA STORE GOVT,COLLEGE PANKSHIN');
        $ward147 = $this->wardModel->create('BELNING NORTH', $lga13, $center75);
        $ward148 = $this->wardModel->create('WUCHENBE', $lga13, $center75);
        $ward149 = $this->wardModel->create('DOKPAL', $lga13, $center75);
        $ward150 = $this->wardModel->create('CHIGWONG', $lga13, $center75);
        $center76 = $this->rCenterModel->create('PADP STORE DYIS');
        $ward151 = $this->wardModel->create('JIBLIK', $lga13, $center76);
        $ward152 = $this->wardModel->create('LANKAN', $lga13, $center76);
        $center77 = $this->rCenterModel->create('PADP STORE LONGKAT');
        $ward153 = $this->wardModel->create('CHIP', $lga13, $center77);
        $ward154 = $this->wardModel->create('TAL', $lga13, $center77);
        $ward155 = $this->wardModel->create('BELNING SOUTH', $lga13, $center77);
        $center78 = $this->rCenterModel->create('GOVT.COLLEGE PKN');
        $ward156 = $this->wardModel->create('KANGSHU', $lga13, $center78);
        $ward157 = $this->wardModel->create('KADUNG', $lga13, $center78);
        $ward158 = $this->wardModel->create('FIER UPPER', $lga13, $center78);
        $center79 = $this->rCenterModel->create('HOME ECONOMIC STORE');
        $ward159 = $this->wardModel->create('PANKSHIN CENTRAL', $lga13, $center79);
        $ward160 = $this->wardModel->create('WOKKOS', $lga13, $center79);

        $lga14 = $this->localGovernmentModel->create("QUA'AN-PAN LGA");
        $center80 = $this->rCenterModel->create('KWANDE STORE NUNAS');
        $ward161 = $this->wardModel->create('KWANDE', $lga14, $center80);
        $ward162 = $this->wardModel->create('KURGWI', $lga14, $center80);
        $center81 = $this->rCenterModel->create('KWANDE STORE NUNAS');
        $ward163 = $this->wardModel->create('NAMU', $lga14, $center81);
        $center82 = $this->rCenterModel->create('DOEMAK TOWN');
        $ward164 = $this->wardModel->create('DOEMAK GOESHIN', $lga14, $center82);
        $ward165 = $this->wardModel->create('DOEMAK KOPLONG', $lga14, $center82);
        $center83 = $this->rCenterModel->create('DOEMAK TOWN');
        $ward166 = $this->wardModel->create('KWALLA MOEDA', $lga14, $center83);
        $ward167 = $this->wardModel->create('KWALLA YITLAR', $lga14, $center83);
        $center84 = $this->rCenterModel->create('DOKAN');
        $ward168 = $this->wardModel->create('DOKAN KASUWA KWA', $lga14, $center84);
        $ward169 = $this->wardModel->create('KWANG', $lga14, $center84);
        $ward170 = $this->wardModel->create('BWALL', $lga14, $center84);

        $lga15 = $this->localGovernmentModel->create('RIYOM LGC');
        $center85 = $this->rCenterModel->create('RIYOM TOWN MBS');
        $ward171 = $this->wardModel->create('RITOM', $lga15, $center85);
        $ward172 = $this->wardModel->create('TAHOSS', $lga15, $center85);
        $center86 = $this->rCenterModel->create('RIYOM LGC STORE MBS');
        $ward173 = $this->wardModel->create('JOL/KWI', $lga15, $center86);
        $ward174 = $this->wardModel->create('SOPP', $lga15, $center86);
        $ward175 = $this->wardModel->create('SHARUBUTU', $lga15, $center86);
        $center87 = $this->rCenterModel->create('GAWURI TOWN MBS');
        $ward176 = $this->wardModel->create('ATTAKAR', $lga15, $center87);
        $ward177 = $this->wardModel->create('RAHOSS', $lga15, $center87);
        $center88 = $this->rCenterModel->create('PADP STORE GANAWURI MBS');
        $ward178 = $this->wardModel->create('DANTO', $lga15, $center88);
        $ward179 = $this->wardModel->create('BUM', $lga15, $center88);

        $lga16 = $this->localGovernmentModel->create('SHENDAM LGC');
        $center89 = $this->rCenterModel->create('PADP STORE YELWA NUNAS');
        $ward180 = $this->wardModel->create('YELWA', $lga16, $center89);
        $center90 = $this->rCenterModel->create('MOA STORE I KWANSAN NUNAS');
        $ward181 = $this->wardModel->create('KURUNGBOU A', $lga16, $center90);
        $ward182 = $this->wardModel->create('KURUNGBOU B', $lga16, $center90);
        $center91 = $this->rCenterModel->create('MOA SROE II KWANSAN NUNAS');
        $ward183 = $this->wardModel->create('KALONG', $lga16, $center91);
        $ward184 = $this->wardModel->create('MOEKAT', $lga16, $center91);
        $center92 = $this->rCenterModel->create('SHENDAM TOWN A NUNAS');
        $ward185 = $this->wardModel->create('KALONG', $lga16, $center92);
        $ward186 = $this->wardModel->create('MOEKAT', $lga16, $center92);
        $center93 = $this->rCenterModel->create('SHENDAM TOWN B NUNAS');
        $ward187 = $this->wardModel->create('POESHIOP', $lga16, $center93);
        $ward188 = $this->wardModel->create('PANGSHOM', $lga16, $center93);
        $center94 = $this->rCenterModel->create('PADP OFFICE SHENDAM');
        $ward189 = $this->wardModel->create('SHIMANKER', $lga16, $center94);
        $center95 = $this->rCenterModel->create('FARM TRANING CENTER GIDAN ADAMU');
        $ward190 = $this->wardModel->create('PANSHOM DOKA', $lga16, $center95);

        $lga17 = $this->localGovernmentModel->create('WASE LGA');
        $center96 = $this->rCenterModel->create('COOP STORE 2 WASE SHANKAT');
        $ward191 = $this->wardModel->create('BASHAR', $lga17, $center96);
        $ward192 = $this->wardModel->create('GUDUS', $lga17, $center96);
        $ward193 = $this->wardModel->create('NYALUM', $lga17, $center96);
        $ward194 = $this->wardModel->create('KAMPANI', $lga17, $center96);
        $ward195 = $this->wardModel->create('YOLA WEST', $lga17, $center96);
        $center97 = $this->rCenterModel->create('COOP STORE 2 WASE SHANKAT');
        $ward196 = $this->wardModel->create('MAVO', $lga17, $center97);
        $ward197 = $this->wardModel->create('DANBIRAN', $lga17, $center97);
        $ward198 = $this->wardModel->create('WASE TOFA', $lga17, $center97);
        $ward199 = $this->wardModel->create('KAYAMBANA', $lga17, $center97);
        $center98 = $this->rCenterModel->create('KADARKO TOWN  SHANKAT');
        $ward200 = $this->wardModel->create('KADAR KO', $lga17, $center98);
        $ward201 = $this->wardModel->create('KUMBONG', $lga17, $center98);
        $ward202 = $this->wardModel->create('KUMBUR', $lga17, $center98);
        $ward203 = $this->wardModel->create('SALUWE', $lga17, $center98);
    }
}
